### ISSUE TITLE
Import of exported SNS Topics is broken

### ISSUE THREAD

**Issue by lttoshev** [ACloudGuru/serverless-plugin-aws-alerts#105]
# This is a Bug Report

## Description

So this feature was introduced with #77 but it doesn't work with the suggested configuration:
```
topics:
  alarm:
    topic:
      Fn::ImportValue: "exported-topic"
```
Serverless breaks with the following error: `TypeError : topic.indexOf is not a function`
I did some digging in the code and found the reason: 
https://github.com/ACloudGuru/serverless-plugin-aws-alerts/blob/355e61da3fca74095cbc74aafaaad1187a1e7657/src/index.js#L178
The lookup for 'Fn::ImportValue' is wrong which causes the code to break in the following line:
https://github.com/ACloudGuru/serverless-plugin-aws-alerts/blob/355e61da3fca74095cbc74aafaaad1187a1e7657/src/index.js#L184

An ugly workaround for this one is:
```
topics:
  alarm:
    Fn::ImportValue: true # or something else it doesn't matter
    topic:
      Fn::ImportValue: "exported-topic"
```

## Additional Data

* ***Serverless Framework Version***: 1.43.0

**Comment by adikari** [comment]
@lttoshev can yo create a PR fixing this?
